'\" t
.\"     Title: pam_fingerprint-gui
.\"    Author: Wolfgang Ullrich <contact@ullrich-online.cc>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: September 16, 2014
.\"    Manual: User Manuals
.\"    Source: Fingerprint GUI 1.00
.\"  Language: English
.\"
.TH "PAM_FINGERPRINT\-GUI" "8" "September 16, 2014" "Fingerprint GUI 1\&.00" "User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pam_fingerprint-gui \- authenticate users based on their fingerprint
.SH "SYNOPSIS"
.HP \w'\fBpam_fingerprint\-gui\&.so\fR\ 'u
\fBpam_fingerprint\-gui\&.so\fR [\fB\-d\fR | \fB\-\-debug\fR] [\fBtry_first_identified\fR]
.SH "DESCRIPTION"
.PP
\fBpam_fingerprint\-gui\fR
is a PAM module that can authenticate users by their fingerprints\&. If the given fingerprint scan matches one of the previously stored fingerprints data (\&.bir format) for a user, the username is stored in the PAM stack and the module returns PAM_SUCCESS\&. The module requests swiping finger and/or typing in the password at the same time\&. The user can get authenticated using either of these methods\&. If a password is typed, the module stores the password in the PAM stack and returns PAM_IGNORE, so that the password can be checked by subsequent modules on the stack\&.
.PP
Depending on the environment while authentication is requested and the service to be authenticated,
\fBpam_fingerprint\-gui\fR
requests password and finger\-swipe through a GUI widget or a console prompt\&.
.PP
If no fingerprint scanner device is connected to the system or no fingerprint data was found for the user to be authenticated,
\fBpam_fingerprint\-gui\fR
returns PAM_AUTHINFO_UNAVAIL\&.
.SH "OPTIONS"
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
Send debugging information to syslog, using the auth facility\&. Depending on system settings the output may end up in
/var/log/auth\&.log,
/var/log/messages
or
/var/log/syslog\&.
.RE
.PP
\fBtry_first_identified\fR
.RS 4
If
\fBpam_fingerprint\-gui\fR
is called more than once in a PAM stack and the given user was identified/authenticated by his/her fingerprint in a previous call already, the module returns PAM_SUCCESS immediately without requesting a password or finger\-swipe again\&.
.RE
.SH "BUGS"
.PP
Bugs can be sent directly to the developer or submitted at
\m[blue]\fB\%http://home.ullrich-online.cc/fingerprint/Forum/\fR\m[]
\&.
.SH "SEE ALSO"
.PP

\fBfingerprint-gui\fR(1),
\fBfingerprint-identifier\fR(1)
.SH "AUTHORS"
.PP
\fBWolfgang Ullrich\fR <\&contact@ullrich\-online\&.cc\&>
.RS 4
Developer
.RE
.PP
\fBDavid Jurenka\fR
.RS 4
Manual pages and Debian packaging
.RE
