debian/pam-configs/*                          usr/share/pam-configs
lib/security
usr/bin
usr/lib/fingerprint-gui/fingerprint-helper    usr/libexec/fingerprint-gui
usr/lib/fingerprint-gui/fingerprint-plugin    usr/libexec/fingerprint-gui
usr/lib/fingerprint-gui/fingerprint-rw        usr/libexec/fingerprint-gui
usr/lib/fingerprint-gui/fingerprint-rw-write  usr/libexec/fingerprint-gui
usr/lib/fingerprint-gui/fingerprint-rw-read   usr/libexec/fingerprint-gui
usr/share
var/lib
